language: python
cache: pip

python:
 - pypy3
 - 3.9
 - 3.8
 - 3.7
 - 3.6

install:
 - pip install -U flake8
 - pip install -Ur requirements.txt

script:
 # Static analysis
 - flake8 --statistics --count .
 # Test run
 - python ci-medals.py

matrix:
  fast_finish: true
