language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - 3.9-dev
 - 3.8
 - 3.7
 - 3.6

install:
 - pip install -U pyflakes pycodestyle

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
